// examples/svelte-style-component/src/App.svelte
<script lang="ts">
    import Mobile from './Mobile.svelte';
    import Tablet from './Tablet.svelte';
    import Desktop from './Desktop.svelte';
    import mq from 'svelte-mq';

    const Style = mq({
        mobile: Mobile,
        tablet: Tablet,
        desktop: Desktop,
    });

    console.log(Style);
</script>

<svelte:component this={$Style}>
    <div class={`item red`}></div>
    <div class={`item green`}></div>
    <div class={`item blue`}></div>
</svelte:component>

// examples/react-css-modules/src/App.tsx
import useMediaQuery from '@mq/react';
import mobile from './mobile.module.css';
import tablet from './tablet.module.css';
import desktop from './desktop.module.css';

function App() {
    const module = useMediaQuery({
        mobile,
        tablet,
        desktop,
    });
    console.log('App');

    return (
        <div className={module.container}>
            <div className={`${module.item} ${module.red}`}></div>
            <div className={`${module.item} ${module.green}`}></div>
            <div className={`${module.item} ${module.blue}`}></div>
        </div>
    );
}

export default App;
